package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.36

import (
	"context"
	"fmt"
	"go-task/graph/model"
)

// CreateLabel is the resolver for the createLabel field.
func (r *mutationResolver) CreateLabel(ctx context.Context, input model.NewLabel) (*model.LabelResponse, error) {

	panic(fmt.Errorf("not implemented: CreateLabel - createLabel"))
}

// CreateLabelTask is the resolver for the createLabelTask field.
func (r *mutationResolver) CreateLabelTask(ctx context.Context, input model.NewLabelTask) (string, error) {
	panic(fmt.Errorf("not implemented: CreateLabelTask - createLabelTask"))
}

// UpdateLabel is the resolver for the updateLabel field.
func (r *mutationResolver) UpdateLabel(ctx context.Context, input model.UpdateLabel) (*model.LabelResponse, error) {
	panic(fmt.Errorf("not implemented: UpdateLabel - updateLabel"))
}

// DeleteLabel is the resolver for the deleteLabel field.
func (r *mutationResolver) DeleteLabel(ctx context.Context, id string) (string, error) {
	panic(fmt.Errorf("not implemented: DeleteLabel - deleteLabel"))
}

// GetLabelByID is the resolver for the getLabelById field.
func (r *queryResolver) GetLabelByID(ctx context.Context, id string) (*model.Label, error) {
	panic(fmt.Errorf("not implemented: GetLabelByID - getLabelById"))
}

// ListLabel is the resolver for the ListLabel field.
func (r *queryResolver) ListLabel(ctx context.Context) ([]*model.Label, error) {
	panic(fmt.Errorf("not implemented: ListLabel - ListLabel"))
}

// ListLabelTask is the resolver for the ListLabelTask field.
func (r *queryResolver) ListLabelTask(ctx context.Context) ([]*model.LabelTaskResponse, error) {
	panic(fmt.Errorf("not implemented: ListLabelTask - ListLabelTask"))
}

// GetLabelTasksByID is the resolver for the getLabelTasksById field.
func (r *queryResolver) GetLabelTasksByID(ctx context.Context, id string) (*model.LabelTaskResponse, error) {
	panic(fmt.Errorf("not implemented: GetLabelTasksByID - getLabelTasksById"))
}
