// Code generated by MockGen. DO NOT EDIT.
// Source: go-task/internal/tasks/repository/postgres (interfaces: Task)

// Package mockdb is a generated GoMock package.
package mockdb

import (
	context "context"
	domain "go-task/domain/task/request"
	domain0 "go-task/domain/task/response"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockTask is a mock of Task interface.
type MockTask struct {
	ctrl     *gomock.Controller
	recorder *MockTaskMockRecorder
}

// MockTaskMockRecorder is the mock recorder for MockTask.
type MockTaskMockRecorder struct {
	mock *MockTask
}

// NewMockTask creates a new mock instance.
func NewMockTask(ctrl *gomock.Controller) *MockTask {
	mock := &MockTask{ctrl: ctrl}
	mock.recorder = &MockTaskMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTask) EXPECT() *MockTaskMockRecorder {
	return m.recorder
}

// CreateTask mocks base method.
func (m *MockTask) CreateTask(arg0 domain.TaskModel) (domain0.TaskResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTask", arg0)
	ret0, _ := ret[0].(domain0.TaskResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTask indicates an expected call of CreateTask.
func (mr *MockTaskMockRecorder) CreateTask(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTask", reflect.TypeOf((*MockTask)(nil).CreateTask), arg0)
}

// DeleteTask mocks base method.
func (m *MockTask) DeleteTask(arg0 uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTask", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTask indicates an expected call of DeleteTask.
func (mr *MockTaskMockRecorder) DeleteTask(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTask", reflect.TypeOf((*MockTask)(nil).DeleteTask), arg0)
}

// FetchTask mocks base method.
func (m *MockTask) FetchTask() ([]domain0.TaskResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchTask")
	ret0, _ := ret[0].([]domain0.TaskResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchTask indicates an expected call of FetchTask.
func (mr *MockTaskMockRecorder) FetchTask() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchTask", reflect.TypeOf((*MockTask)(nil).FetchTask))
}

// FetchTaskByID mocks base method.
func (m *MockTask) FetchTaskByID(arg0 context.Context, arg1 uuid.UUID) (domain0.TaskResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchTaskByID", arg0, arg1)
	ret0, _ := ret[0].(domain0.TaskResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchTaskByID indicates an expected call of FetchTaskByID.
func (mr *MockTaskMockRecorder) FetchTaskByID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchTaskByID", reflect.TypeOf((*MockTask)(nil).FetchTaskByID), arg0, arg1)
}

// UpdateTask mocks base method.
func (m *MockTask) UpdateTask(arg0 domain.UpdateTaskModel, arg1 uuid.UUID) (domain0.TaskResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTask", arg0, arg1)
	ret0, _ := ret[0].(domain0.TaskResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateTask indicates an expected call of UpdateTask.
func (mr *MockTaskMockRecorder) UpdateTask(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTask", reflect.TypeOf((*MockTask)(nil).UpdateTask), arg0, arg1)
}
