// Code generated by MockGen. DO NOT EDIT.
// Source: go-task/internal/auths/repository/postgres (interfaces: Authentication)

// Package mockdb is a generated GoMock package.
package mockdb

import (
	domain "go-task/domain/auths/request"
	domain0 "go-task/domain/auths/response"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockAuthentication is a mock of Authentication interface.
type MockAuthentication struct {
	ctrl     *gomock.Controller
	recorder *MockAuthenticationMockRecorder
}

// MockAuthenticationMockRecorder is the mock recorder for MockAuthentication.
type MockAuthenticationMockRecorder struct {
	mock *MockAuthentication
}

// NewMockAuthentication creates a new mock instance.
func NewMockAuthentication(ctrl *gomock.Controller) *MockAuthentication {
	mock := &MockAuthentication{ctrl: ctrl}
	mock.recorder = &MockAuthenticationMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthentication) EXPECT() *MockAuthenticationMockRecorder {
	return m.recorder
}

// login mocks base method.
func (m *MockAuthentication) login(arg0 domain.LoginModel) (domain0.RegisterResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "login", arg0)
	ret0, _ := ret[0].(domain0.RegisterResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// login indicates an expected call of login.
func (mr *MockAuthenticationMockRecorder) login(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "login", reflect.TypeOf((*MockAuthentication)(nil).login), arg0)
}

// register mocks base method.
func (m *MockAuthentication) register(arg0 domain.RegisterModel) (domain0.RegisterResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "register", arg0)
	ret0, _ := ret[0].(domain0.RegisterResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// register indicates an expected call of register.
func (mr *MockAuthenticationMockRecorder) register(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "register", reflect.TypeOf((*MockAuthentication)(nil).register), arg0)
}
